# Generated by Django 4.1 on 2023-09-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_text', models.CharField(max_length=200)),
                ('date_posted', models.DateTimeField(verbose_name='date posted')),
                ('ad_type', models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell'), ('None', 'None - Placeholder')], max_length=4)),
            ],
        ),
    ]
