# Generated by Django 4.1 on 2023-09-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classified_ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='user',
            field=models.CharField(default='PLACEHOLDER', max_length=200),
        ),
        migrations.AlterField(
            model_name='ad',
            name='ad_type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], max_length=4),
        ),
    ]
