# Generated by Django 4.1 on 2023-09-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classified_ads', '0002_ad_user_alter_ad_ad_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='user',
            field=models.CharField(max_length=200),
        ),
    ]
