# Generated by Django 4.1 on 2023-09-10 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classified_ads', '0003_alter_ad_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='ad_text',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='ad',
            name='user',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=1000)),
                ('date_posted', models.DateTimeField(verbose_name='date posted')),
                ('user', models.CharField(max_length=30)),
                ('parent_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classified_ads.ad')),
            ],
        ),
    ]
