# Generated by Django 4.1 on 2023-09-16 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classified_ads', '0004_alter_ad_ad_text_alter_ad_user_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_posted']},
        ),
    ]
