# Generated by Django 4.1 on 2023-09-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classified_ads', '0005_init_postable_abstract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='date_posted',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_posted',
            field=models.DateTimeField(),
        ),
    ]
