# Generated by Django 4.1 on 2023-09-16 02:32

from django.db import migrations


def move_text(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Ad = apps.get_model('classified_ads', 'Ad')
    Comment = apps.get_model('classified_ads', 'Comment')
    for ad in Ad.objects.all():
        ad.text = ad.ad_text
        ad.save()
    for comment in Comment.objects.all():
        comment.text = comment.comment_text
        comment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('classified_ads', '0007_add_text_field'),
    ]

    operations = [
        migrations.RunPython(move_text),
    ]
