# Generated by Django 4.1 on 2023-09-16 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classified_ads', '0008_auto_20230915_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='ad_text',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_text',
        ),
        migrations.AlterField(
            model_name='ad',
            name='text',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=1000),
        ),
    ]
