# Generated by Django 4.1 on 2023-09-16 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classified_ads', '0009_ad_comment_inherit_postable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
