# Generated by Django 4.1 on 2023-09-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classified_ads', '0012_alter_ad_user_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
